development:
  adapter: mysql2
  encoding: utf8
  host: mysql18.redehost.com.br
  port: 3306
  database: minha_carreira
  username: joaoroberto32
  password: carreira2012

test:
  adapter: mysql2
  encoding: utf8
  host: mysql18.redehost.com.br
  port: 3306
  database: minha_carreira
  username: joaoroberto32
  password: carreira2012

production:
  adapter: mysql2
  encoding: utf8
  host: mysql18.redehost.com.br
  port: 3306
  database: minha_carreira
  username: joaoroberto32
  password: carreira2012